### PR TITLE
Fix wrong SVG url

### PR DESCRIPTION
**Pull request by doggy8088**
https://dotnetnew.azurewebsites.net

image

### CODE REVIEW

**Comment by sayedihashimi** [comment]
Thanks for the PR, I've merged it.

**Comment by doggy8088** [comment]
@sayedihashimi the website looks like not update yet. https://dotnetnew.azurewebsites.net

**Comment by sayedihashimi** [comment]
I just realized that you sent the PR to the wrong branch. It should have gone to master. The globaltool branch was a prototype I was playing around with.

**Comment by sayedihashimi** [comment]
I have actually already fixed this in master on [9/13](df21a874783b3fbfb011bd8459023116204cbd85), I just haven't deployed it yet. I will go ahead and do that now.

**Comment by sayedihashimi** [comment]
OK its been updated.

**Pull request merged**
